### PR TITLE
Use sendMultipartTextMessage() if the message needs to be sent in parts

### PR DESCRIPTION
**Pull request by complex857**
I found that if i have a long message (or a relatively short one with accented Hungarian characters) the message is not sent with empty intent while _is_ sent if I use the built-in messages app (with `"INTENT"` intent). 
Did some digging and found that if I use the [`sendMultipartTextMessage()`](https://developer.android.com/reference/android/telephony/SmsManager.html#sendMultipartTextMessage%28java.lang.String,%20java.lang.String,%20java.util.ArrayList%3Cjava.lang.String%3E,%20java.util.ArrayList%3Candroid.app.PendingIntent%3E,%20java.util.ArrayList%3Candroid.app.PendingIntent%3E%29) the message is sent as expected.

I only dabble in java, so please feel free to correct any obvious mistake i made. With the current implementation the `callbackContext.sendPluginResult()` (in execute) will be called multiple times since the `sendMultipartTextMessage()` [expects to receive](https://developer.android.com/reference/android/telephony/SmsManager.html#sendMultipartTextMessage%28java.lang.String,%20java.lang.String,%20java.util.ArrayList%3Cjava.lang.String%3E,%20java.util.ArrayList%3Candroid.app.PendingIntent%3E,%20java.util.ArrayList%3Candroid.app.PendingIntent%3E%29) multiple `PendingIndent`s "one for each message part" according to the docs. This does not seemed to cause a problem for me.

I've only tested it a Galaxy S2 with Android 4.4.4 (cyanogenmod).

### CODE REVIEW

**Comment by radiegtya** [comment]
not working when I left the intent blank

here are my code:
```
var number = "085641278479";
        var message = "hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi2 cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi3 cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi4 cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi cuk hi5cuk hi cuk hi cuk hi cuk hi cuk hi cuk";
        var intent = ''; //leave empty for sending sms using default intent
        var success = function() {
            alert('Message sent successfully');
        };
        var error = function(e) {
            alert('Message Failed:' + e);
        };
        sms.sendMultipartTextMessage(number, message, intent, success, error);
```

**Comment by complex857** [comment]
Hi @radiegtya, thank you for reporting! Do you receive any useful error messages in the error callback? Or it's just fails silently?

**Comment by dbaq** [comment]
no there is an error because a permission was missing and the callbacks are fired multiple times, I fixed everything on the new repo, please let's follow up there: https://github.com/cordova-sms/cordova-sms-plugin/issues/7

**Comment by complex857** [comment]
@dbaq, Oh i see, thank' you for maintaining this and sorry for the mess, I only dabble in android.

**Comment by radiegtya** [comment]
@dbaq : I have tried your branch, but unfortunately still failed to sending message :(

**Comment by dbaq** [comment]
@radiegtya you should comment on the new repo, this one is not maintained anymore

let's followup there: https://github.com/cordova-sms/cordova-sms-plugin/issues/7

**Pull request merged**
